# Generated by Django 6.0.6 on 2026-06-23 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
