# Generated by Django 6.0.6 on 2026-06-23 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_category',
            field=models.CharField(blank=True, choices=[('royalty_and_payment', 'Royalty & Payments'), ('isbn_and_metadata_issues', 'ISBN & Metadata Issues'), ('printing_and_quality', ' Printing & Quality'), ('distribution_and_availability', 'Distribution & Availability'), ('book_status_and_production_updatesBook Status & Production Updates', 'Book Status And Production Updates'), ('general_inquery', 'General Inquery')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_priority',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'medium'), ('low', 'Low')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'medium'), ('low', 'Low')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('royalty_and_payment', 'Royalty & Payments'), ('isbn_and_metadata_issues', 'ISBN & Metadata Issues'), ('printing_and_quality', ' Printing & Quality'), ('distribution_and_availability', 'Distribution & Availability'), ('book_status_and_production_updatesBook Status & Production Updates', 'Book Status And Production Updates'), ('general_inquery', 'General Inquery')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tickets.ticket')),
            ],
        ),
    ]
