# Generated by Django 6.0.6 on 2026-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_ai_category_ticket_ai_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketresponse',
            name='ai_draft_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ai_category',
            field=models.CharField(blank=True, choices=[('royalty_and_payment', 'Royalty & Payments'), ('isbn_and_metadata_issues', 'ISBN & Metadata Issues'), ('printing_and_quality', ' Printing & Quality'), ('distribution_and_availability', 'Distribution & Availability'), ('book_status_and_production_updates', 'Book Status & Production Updates'), ('general_inquery', 'General Inquery')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('royalty_and_payment', 'Royalty & Payments'), ('isbn_and_metadata_issues', 'ISBN & Metadata Issues'), ('printing_and_quality', ' Printing & Quality'), ('distribution_and_availability', 'Distribution & Availability'), ('book_status_and_production_updates', 'Book Status & Production Updates'), ('general_inquery', 'General Inquery')], max_length=100, null=True),
        ),
    ]
