# Generated by Django 6.0.6 on 2026-06-23 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('genre', models.CharField(max_length=100)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('cover_design', 'In Production - Cover Design'), ('typesetting', 'In Production - Typesetting')], max_length=20)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('author_royalty_per_copy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_copies_sold', models.PositiveIntegerField(default=0)),
                ('royalty_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_royalty_payout_date', models.DateField(blank=True, null=True)),
                ('print_partner', models.CharField(blank=True, max_length=50, null=True)),
                ('available_on', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
